# This is a basic workflow to help you get started with Actions

name: passing job values

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pass_in_one_job:
    runs-on: ubuntu-latest
    outputs:
      COLOR: ${{ steps.color-selector.outputs.COLOR }}
    steps:
      - name: Set color
        id: color-selector
        run: echo "COLOR=RED" >> "$GITHUB_OUTPUT"

      - name: Get color
        env:
          COLOR: ${{ steps.color-selector.outputs.COLOR }}
        run: echo "The selected color is $COLOR"

  producer:
    needs: pass_in_one_job
    runs-on: ubuntu-latest
    steps:
      - name: Make a sentence
        id: sentence_maker
        env:
          COLOR: ${{ needs.pass_in_one_job.outputs.COLOR }}
        run: |
          echo "message=The color is ${{ needs.pass_in_one_job.outputs.COLOR }}" >> "$GITHUB_OUTPUT"

  consumer:
    needs: producer
    runs-on: ubuntu-latest
    steps:
      - name: Print the message
        env:
          message: ${{ needs.producer.outputs.message }}
        run: |
          echo $message

  job_1:
    name: Add 3 and 7
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 3 + 7 > file.txt

      - name: Upload artifact file config
        uses: actions/upload-artifact@v4
        with:
          name: file
          path: file.txt

  job_2:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download artifact file
        uses: actions/download-artifact@v5
        with:
          name: file
      - shell: bash
        run: |
          value=`cat file.txt`
          echo $(expr $value \* 9)